spring:
  application:
    name: charitan-api-gateway
  cloud:
    consul:
      host: ${CONSUL_HOST:service-registry}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true 
        register: true 
        service-name: charitan-api-gateway

    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowed-headers:
              - "Access-Control-Allow-Origin"
              - "Content-Type"
              - "Authorization"

  rabbitmq:
    host: message-broker
    port: 5672
    username: ${MESSAGE_BROKER_USER}
    password: ${MESSAGE_BROKER_PASSWORD}

server:
  port: 8080
